<?php

namespace Karaev\Vehicle\Infrastructure\Eloquent\Model;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;
use Karaev\Vehicle\Infrastructure\Eloquent\Factories\VehicleImageFactory;

class VehicleImage extends Model
{
    use HasFactory;

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class);
    }

    public function delete()
    {
        $this->deleteModeFile();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public static function factory($count = null, $state = [])
    {
        return VehicleImageFactory::new();
    }

    public function deleteModeFile()
    {
        if(Storage::exists($this->name)) {
            Storage::delete($this->name);
        }
    }
}
