# Use the official Ubuntu base image
FROM node:20-alpine

WORKDIR /var/www/html

# Defaults to production, docker-compose overrides this to development on build and run.
ARG NODE_ENV=production


# Define the command to run your Node.js CLI tool
CMD tail -f /dev/null
